language: c

branches:
  only:
    - unittest

sudo: required
services:
  - docker

before_script:
  # git submodule init && git submodule update  # done automaticall by travis
  - cd dscripts && git checkout master && git pull && cd ..
  - cp conf.sh.default conf.sh
  - dscripts/build.sh -u

script:
  - dscripts/run.sh -ipV /tests/init_sample_config_phoAt.sh
  - dscripts/run.sh -ipV /tests/init_sample_config_phoAt2.sh
  - dscripts/run.sh -pV  # run slapd in background
  - sleep 2
  - dscripts/exec.sh /tests/init_sample_data_phoAt.sh
  - dscripts/exec.sh /tests/dump_testuser.sh
  - dscripts/exec.sh /tests/authn_testuser.sh
  - dscripts/exec.sh python3.4 /tests/test1.py
  - dscripts/exec.sh python 3.4 /tests/pyunit.py
  # dscripts/exec.sh /tests/init_additional_data.sh
  # dscripts/exec.sh python 3.4 /tests/pyunit.py
  # dscripts/exec.sh /tests/init_additional_data2.sh
  # dscripts/exec.sh python 3.4 /tests/pyunit.py


after_success:
  # - if [ $TRAVIS_BRANCH" == "unittest" ]; then
  #  docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" || travis_terminate $?;
  #  docker push $IMAGENAME; || travis_terminate $?;
  #  echo "pushed $IMAGENAME to docker hub";
